version: "3"

services:
  app:
    build: app/
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
  server:
    build: server/
    ports:
      - 3000:3000
      - 8081:8081
    environment:
      - NODE_ENV=production
