apps:
  - script: "index.js"
    name: "production-app"
    exec_mode: "fork"
    instances: "1"
    env:
      NODE_ENV: "production"
  - script: "bot.js"
    name: "bot"
    exec_mode: "fork"
    instances: "1"
